name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pyunit tests
      env:
        GITHUBAPI: ${{ secrets.GITHUBAPI }}
      run: python -m unittest

    - name: Test with pytest
      env:
        GITHUBAPI: ${{ secrets.GITHUBAPI }}
      run: python validate.py